service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: batch-service-1-vhmdwutjrt
  name: batch-service-1-vhmdwutjrt
  selector: batch-service-1-vhmdwutjrt
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
batch:
  name: batch-service-1-vhmdwutjrt
  image:
    name: batch-service-1-vhmdwutjrt
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: batch-service-1-vhmdwutjrt
  repo:
    url: -@imageRepoName@-
  backing: 
  volume:
    name: pvc-batch-service-1-vhmdwutjrt
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
pvc:
  name: pvc-batch-service-1-vhmdwutjrt
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
